### ISSUE TITLE
GDPR

### ISSUE THREAD

**Issue by oleob** [NTNUI-Kite/kite-frontend#8]
Add button for GDPR complaints

**Comment by emilps** [comment]
https://gdprchecklist.io/

**Comment by Gdewilde** [comment]
Or https://gdprform.io

**Comment by Gdewilde** [comment]
Or https://gdprform.io

**Comment by oleob** [comment]
staph

**Comment by emilps** [comment]
Needs privacylist, then finished

**Comment by oleob** [comment]
GDPR is a scam
